export {default as AdminDashboardPage} from './admin/dashboard'
export {default as AdminUsersPage} from './admin/users'
export {default as AdminUserDetailsPage} from './admin/users/details'
export {default as AdminHabitsPage} from './admin/habits'
export {default as AdminHabitDetailsPage} from './admin/habits/details'
export {default as AdminHabitTracksPage} from './admin/habit-tracks'
export {default as AdminHabitTrackDetailsPage} from './admin/habit-tracks/details'

export {default as LoadingPage} from './common/loading'
export {default as ErrorPage} from './common/error-page'

export {default as UserProfilePage} from './user/profile'
export {default as UserHabitTrackPage} from './user/habit-track'
export {default as UserHabitTrackDetailsPage} from './user/habit-track-details'
export {default as UserHabitsPage} from './user/habits'

export {default as AboutPage} from './visitor/about'
export {default as HomePage} from './visitor/home'
export {default as LoginPage} from './visitor/login'
export {default as RegisterPage} from './visitor/register'
export {default as PrivacyPolicyPage} from './visitor/privacy-policy'